name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Se actualiza cada medianoche
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Configuración estética
          user: BR444N
          template: classic
          base: "" # No queremos las stats generales, solo los proyectos
          config_timezone: America/Mexico_City
          
          # Sección de Proyectos Destacados (Pinned)
          plugin_projects: yes
          plugin_projects_limit: 4
          
          # Personalización de colores 
          # Amarillo #FFE953 para los acentos
          config_order: projects
          queries_common: |
            {
              "color_primary": "#FFE953",
              "color_text": "#ffffff",
              "color_background": "#0d1117"
            }
          
          # Archivo de salida
          filename: github-metrics.svg
