name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BR444N
          template: classic
          base: ""
          
          # REPOSITORIOS, NO PROJECTS
          plugin_repositories: yes
          plugin_repositories_pinned: 4
          
          # DISEÃ‘O
          config_order: repositories
          queries_common: |
            {
              "color_primary": "#FFE953",
              "color_text": "#ffffff",
              "color_background": "#0d1117"
            }
          filename: github-metrics.svg
